# permissions for end users to edit pgdeployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pgdeployer-editor-role
rules:
- apiGroups:
  - pgdeployer.example.com
  resources:
  - pgdeployers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgdeployer.example.com
  resources:
  - pgdeployers/status
  verbs:
  - get
