# permissions for end users to view pgdeployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pgdeployer-viewer-role
rules:
- apiGroups:
  - pgdeployer.example.com
  resources:
  - pgdeployers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pgdeployer.example.com
  resources:
  - pgdeployers/status
  verbs:
  - get
